import type { SlideData, SourceItem } from "../types/presentation";

const notes = (
  duration: string,
  points: string[],
  bridgeFrom: string,
  transitionTo: string,
  action?: string,
) => ({ duration, points, bridgeFrom, transitionTo, action });

export const slides: SlideData[] = [
  {
    id: "hero",
    chapter: "opening",
    chapterLabel: "开场",
    pageNumber: 1,
    eyebrow: "FULLGOAL · AI SHARING SESSION",
    title: "AI不只是聊天",
    subtitle: "从Chat规划、Agent执行到Skill复用",
    keyMessage: "人定目标，Chat帮助想清楚，Agent负责做出来，Skill负责重复使用。",
    body: "一套面向普通同事的人机协作方法，以及一个真实Skill的设计过程。",
    bullets: ["内部分享", "2026"],
    visualType: "hero",
    sourceNote: "内部分享 · 请勿外传",
    speakerNotes: notes(
      "1:00",
      ["今天不讲模型参数，讲一套任何同事都能上手的工作方法。", "重点不是让AI替代谁，而是重新安排人、Chat、Agent与Skill的角色。"],
      "欢迎大家参加今天的内部分享。",
      "先用三件事建立今天的路线图。",
      "点击“开始分享”进入目录。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "agenda",
    chapter: "opening",
    chapterLabel: "开场",
    pageNumber: 2,
    eyebrow: "TODAY'S AGENDA",
    title: "今天主要分享三件事",
    subtitle: "从概念、方法到一个真实案例",
    keyMessage: "先看懂AI如何从回答问题走向完成工作，再看人怎样把复杂任务控制住。",
    body: "三个章节可点击跳转。",
    bullets: ["认识AI", "我的协作方法", "FullGoal PPT Master"],
    visualType: "agenda",
    sourceNote: "FG AI Sharing Session",
    speakerNotes: notes(
      "1:00",
      ["第一部分统一几个容易混淆的AI概念。", "第二部分分享我实际使用的六步SOP。", "第三部分拆解FullGoal PPT Master如何从需求演进成Skill。"],
      "刚才先给出了今天的总命题。",
      "先从AI正在发生的变化开始。",
      "可点击三个章节编号跳转。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "ai-shift",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 3,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "AI的变化，不只是回答更聪明，而是开始能够完成工作",
    subtitle: "从生成，到理解、行动与持续执行",
    keyMessage: "AI正在从“给答案的工具”，变成“参与工作过程的系统”。",
    body: "能力的关键变化，是从单次输出走向围绕目标的连续工作。",
    bullets: ["生成", "理解", "行动", "持续执行"],
    visualType: "ai-shift",
    sourceNote: "概念梳理：AI能力演进",
    speakerNotes: notes(
      "1:20",
      ["过去我们最熟悉的是让AI生成一段文字。", "现在AI还能读取项目上下文、调用工具，并根据结果决定下一步。", "变化的核心不是更会聊，而是开始进入工作过程。"],
      "目录把今天分成了三个部分。",
      "要理解这种变化，需要先区分模型、Chat与Agent。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "model-chat-agent",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 4,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "模型、Chat和Agent，不是三个互相替代的产品",
    subtitle: "它们更像一条从能力核心到工作系统的连续关系",
    keyMessage: "模型决定它有多聪明，上下文决定它能看到什么，工具决定它能做什么。",
    body: "Model负责理解与生成；Chat让人方便使用模型；Agent围绕目标持续规划并调用工具。",
    bullets: ["Model / LLM", "Chat", "Agent"],
    visualType: "agent-formula",
    sourceNote: "参考：AI Agent基础框架",
    speakerNotes: notes(
      "1:30",
      ["模型像大脑，Chat是我们最熟悉的使用界面。", "Agent不是另一个更大的模型，它增加了上下文、工具和持续执行。", "右侧公式用大脑、眼睛和手脚帮助记忆。"],
      "上一页讲的是AI从回答走向行动。",
      "接下来把常见的八个概念放到一张地图里。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "concept-map",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 5,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "八个概念，基本可以看懂现在大多数AI产品",
    subtitle: "围绕Agent理解能力、材料、指令、工具与工作环境",
    keyMessage: "Agent的表现，不只取决于模型，也取决于它被放进了什么工作系统。",
    body: "点击概念节点，查看一句话解释和日常类比。",
    bullets: ["Model", "Context", "Prompt", "Tool", "API", "MCP", "Skill", "Harness"],
    visualType: "concept-map",
    sourceNote: "概念梳理：Agent工作系统",
    speakerNotes: notes(
      "1:40",
      ["不必一次记住所有缩写，先看它们围绕Agent分别解决什么问题。", "Skill是标准操作手册，Harness更像办公环境与管理制度。", "现场可以点两三个节点，用类比快速解释。"],
      "刚才用三层关系区分了模型、Chat与Agent。",
      "其中API常被提到，下一页单独解释它和API Key。",
      "点击任意概念节点。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "api-key",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 6,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "API是软件之间的窗口，API Key是进入窗口的钥匙",
    subtitle: "接口负责沟通，密钥负责身份与计费",
    keyMessage: "API Key必须放在环境变量或受保护的本地配置中。",
    body: "软件按固定格式发送请求，服务完成处理后返回可继续保存或加工的结果。",
    bullets: ["不要写进公开代码", "不要上传到GitHub", "使用环境变量或受保护配置"],
    visualType: "api-flow",
    sourceNote: "安全示例，不包含真实Key",
    speakerNotes: notes(
      "1:20",
      ["API是软件之间的标准窗口，不需要人手工复制粘贴。", "API Key同时是身份凭证和计费凭证，所以要像密码一样保护。", "页面中的Key是掩码示例，不可使用。"],
      "概念地图里API负责软件之间的连接。",
      "概念清楚后，最后看当前Agent发展的重点。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "agent-trends",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 7,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "现在的前沿重点，已经从“模型能不能做”转向“人如何监督它做”",
    subtitle: "长任务、并行执行、电脑操作、可复用能力与人在环路",
    keyMessage: "Agent越能行动，人的审查、校准和批准就越重要。",
    body: "近期Codex能力示例：Windows桌面应用、Goal Mode、Appshots、浏览器标注、Skills、Computer Use与远程继续任务。",
    bullets: ["Long-running Work", "Parallel Agents", "Computer Use", "Reusable Skills", "Human Steering"],
    visualType: "trend-rail",
    sourceNote: "OpenAI官方产品与帮助文档，2026年",
    speakerNotes: notes(
      "1:30",
      ["能力越强，重点越不只是能否完成，而是如何保持可控。", "并行Agent和电脑操作会放大效率，也会放大错误影响。", "所以Human Steering不是补丁，而是设计核心。"],
      "API让Agent可以连接更多外部能力。",
      "这正好引出第二部分：我如何安排Chat、Agent与人的分工。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "chat-vs-agent",
    chapter: "method",
    chapterLabel: "协作方法",
    pageNumber: 8,
    eyebrow: "PART 02 · CHAT × AGENT",
    title: "Chat和Agent都能思考，但我会刻意让它们承担不同角色",
    subtitle: "Chat帮助想清楚，Agent负责做出来",
    keyMessage: "这种分工不是产品能力限制，而是一种提高复杂任务可控性的工作方法。",
    body: "复杂任务中，人不是退出流程，而是从执行者转向目标制定者和验收者。",
    bullets: ["Chat：顾问 / 架构师", "Agent：执行者 / 项目同事"],
    visualType: "chat-agent",
    sourceNote: "个人工作方法总结",
    speakerNotes: notes(
      "1:35",
      ["Chat阶段允许充分讨论取舍，成本低、改方向快。", "Agent阶段强调读文件、运行工具、测试并交付。", "刻意分工能减少边想边做造成的返工。"],
      "第一部分说明了Agent能做什么。",
      "下面把这套分工展开成六个明确步骤。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "collaboration-sop",
    chapter: "method",
    chapterLabel: "协作方法",
    pageNumber: 9,
    eyebrow: "PART 02 · COLLABORATION SOP",
    title: "人定目标，Chat定方案，Agent做执行，验收控质量，Skill做复用",
    subtitle: "把一次复杂任务拆成六个可停、可改、可验证的阶段",
    keyMessage: "每一步都要说清楚：谁负责、输出什么、如何判定通过。",
    body: "点击六个步骤，查看职责、阶段输出和常见失败。",
    bullets: ["提供材料", "和Chat规划", "人工调整", "Agent执行", "阶段验收", "沉淀为Skill"],
    visualType: "workflow-stepper",
    sourceNote: "个人人机协作SOP",
    speakerNotes: notes(
      "1:50",
      ["第一步不是写Prompt，而是把材料和边界准备好。", "规划后必须有人调整，避免把错误方向自动化。", "最后只有稳定成功的流程才值得沉淀成Skill。"],
      "上一页说明了角色分工。",
      "有了步骤，还需要在关键位置设置阶段门。",
      "点击步骤切换详情，也可用左右方向键。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "stage-gates",
    chapter: "method",
    chapterLabel: "协作方法",
    pageNumber: 10,
    eyebrow: "PART 02 · STAGE-GATE",
    title: "复杂任务不是一次性Prompt，而是一连串“执行—检查—再继续”",
    subtitle: "没有通过当前Gate，就不进入下一阶段",
    keyMessage: "文件、截图、测试和差异记录才是证据，不能用“模型说通过”代替验证。",
    body: "材料完整、逻辑正确、成果符合要求、文件有效、允许发布，五次判断共同保护最终质量。",
    bullets: ["没确认大纲，不进入正式生产", "数据冲突时停止", "目标改变后旧批准失效", "独立证据优先"],
    visualType: "stage-gates",
    sourceNote: "Stage-Gate方法的AI任务应用",
    speakerNotes: notes(
      "1:50",
      ["Gate不是多一道流程，而是减少后期大返工。", "数据冲突、目标变化、文件损坏都应该让任务停下来。", "真正的通过需要独立证据，而不是模型自评。"],
      "六步SOP说明了任务怎么推进。",
      "这些做法背后，其实是成熟项目管理思维的迁移。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "thinking-frameworks",
    chapter: "method",
    chapterLabel: "协作方法",
    pageNumber: 11,
    eyebrow: "PART 02 · THINKING FRAMEWORK",
    title: "这不是多问几次AI，而是把项目管理方法迁移到人机协作",
    subtitle: "需求、上下文、分工、审批、验证与复用共同组成工作系统",
    keyMessage: "好的AI协作，不是把所有事情交给AI，而是重新设计人和AI各自负责的部分。",
    body: "八种思维共同回答四件事：目标是什么、AI看什么、谁来决定、结果如何验证。",
    bullets: ["需求工程", "上下文工程", "Planner–Executor", "Human-in-the-loop", "Stage-Gate", "Evaluation-driven", "Artifact-first", "Skillization"],
    visualType: "thinking-frameworks",
    sourceNote: "方法论归纳",
    speakerNotes: notes(
      "1:35",
      ["这些名词看似很多，实质是把成熟工作方法带进AI协作。", "Artifact-first意味着围绕文件和可检查成果协作。", "Skillization是最后一步，不是第一步。"],
      "上一页强调了阶段门和证据。",
      "接下来用FullGoal PPT Master看这些原则如何落地。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "skill-problem",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 12,
    eyebrow: "PART 03 · FULLGOAL PPT MASTER",
    title: "我最初只是想让AI模仿富国PPT，后来发现真正的问题远不止排版",
    subtitle: "从一次PPT需求，到一个可运行的Skill",
    keyMessage: "目标不是自动套模板，而是在固定品牌骨架下，让AI重点发挥内容组织和视觉表达能力。",
    body: "研究叙事、正式模板、视觉生成、数据准确和质量检查必须进入同一条生产流程。",
    bullets: ["长报告难拆页", "摘抄不等于叙事", "自由生图破坏模板", "图像文字数字不可靠", "长Prompt难复用"],
    visualType: "skill-problem",
    sourceNote: "FullGoal PPT Master公开项目总结",
    speakerNotes: notes(
      "1:35",
      ["最初问题看起来是排版，做下去才发现内容叙事更难。", "模板约束与视觉生成之间存在天然张力。", "因此流程必须同时控制内容、品牌、数据和QA。"],
      "第二部分给出了方法框架。",
      "这个项目经历了五次关键认知升级。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "project-evolution",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 13,
    eyebrow: "PART 03 · PROJECT EVOLUTION",
    title: "项目经历了五次重要认知升级",
    subtitle: "每一次调整都来自上一阶段真实暴露的问题",
    keyMessage: "固定品牌骨架 + AI组织研究内容 + Image-native生成视觉 + 程序保证数据准确。",
    body: "从模仿历史PPT，走到模板分层、研究叙事、人工批准与混合渲染。",
    bullets: ["模仿历史PPT", "分析模板与历史页", "增加研究叙事", "增加批准门禁", "转向Image-native"],
    visualType: "project-evolution",
    sourceNote: "FullGoal PPT Master公开演进记录",
    speakerNotes: notes(
      "1:35",
      ["第一阶段只学到表面排版。", "第三阶段发现最难的是内容怎么展开，而不是图放哪里。", "第五阶段接受可编辑性与视觉完成度之间需要混合路线。"],
      "上一页说明了为什么需要这个Skill。",
      "演进过程中最先锁定的是模板边界。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "template-modes",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 14,
    eyebrow: "PART 03 · TEMPLATE BOUNDARY",
    title: "让AI发挥，不等于让AI重新设计公司的模板",
    subtitle: "模板固定，正文内容区可以选择A / B / C复杂度",
    keyMessage: "A/B/C只能改变正文内容区，不能改变富国模板骨架。",
    body: "Logo、标题区、蓝线、字体、来源、页码和页脚构成固定品牌层。",
    bullets: ["A｜经典研究型", "B｜机制表达型", "C｜综合重点型"],
    visualType: "template-modes",
    sourceNote: "FullGoal PPT Master公开模板策略",
    speakerNotes: notes(
      "1:40",
      ["A/B/C不是三套模板，而是同一骨架里的正文复杂度。", "封面、目录、章节和结束页属于更严格的固定层。", "让AI变化的区域必须被清楚画出来。"],
      "项目演进最终先把不该变化的部分锁住。",
      "边界清楚后，最大的技术路线调整发生在正文视觉。",
      "点击A/B/C查看正文区变化。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "image-native-pivot",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 15,
    eyebrow: "PART 03 · IMAGE-NATIVE PIVOT",
    title: "为了可编辑而组件化，反而做出了一张“像PPT组件拼起来的PNG”",
    subtitle: "组件化可控，Image-native更完整；最终选择混合路线",
    keyMessage: "AI负责视觉，程序负责精确。",
    body: "固定V3品牌骨架 + Image-native正文视觉 + 关键文字、数字、图表与来源的确定性后处理。",
    bullets: ["组件化Renderer", "Image-native", "确定性后处理"],
    visualType: "before-after",
    sourceNote: "抽象示意 · 真实图片可后续替换",
    speakerNotes: notes(
      "1:50",
      ["组件化方便控制数据和转PPT，但空间关系容易僵硬。", "Image-native构图更自然，却不能信任其中的文字和数字。", "最终不是二选一，而是让AI做视觉、程序做精确。"],
      "上一页定义了固定与可变的边界。",
      "这条混合路线已经在一份真实材料上跑通核心链路。",
      "拖动中间滑杆查看抽象Before / After示意。",
    ),
    assetSlots: ["renderer-before", "image-native-after"],
    theme: "soft",
    status: "placeholder",
  },
  {
    id: "ici-case",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 16,
    eyebrow: "PART 03 · ICI CHAPTER 4 CASE",
    title: "Skill已经在真实研究材料上跑通核心链路",
    subtitle: "明确区分已完成结果与尚未完成工作",
    keyMessage: "已完成材料解析、数据核验、13页大纲、代表页测试与品牌区域后处理。",
    body: "尚未完成13页完整视觉稿与最终PPTX还原。",
    bullets: ["146页完整读取", "26个核心数字核验", "13页研究汇报大纲", "2页代表页测试"],
    visualType: "ici-case",
    sourceNote: "用户提供的ICI测试项目脱敏总结",
    speakerNotes: notes(
      "1:50",
      ["这页只陈述已经确认的真实状态。", "材料从事实手册重组为一条研究叙事，而不是简单摘要。", "未完成的13页视觉稿和PPTX必须明确标注。"],
      "混合路线需要用真实材料验证。",
      "要持续复用，就要把流程、规则和脚本组织成Skill。",
    ),
    assetSlots: ["ici-outline", "qa-screenshot"],
    theme: "light",
    status: "partial",
  },
  {
    id: "skill-architecture",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 17,
    eyebrow: "PART 03 · SKILL ARCHITECTURE",
    title: "Skill不是一个长Prompt，而是一套可以被Agent按需调用的工作系统",
    subtitle: "规则、参考、数据结构、脚本与小案例共同组成可复用能力",
    keyMessage: "好的Skill让用户用更短的要求，调用更完整的流程。",
    body: "通过渐进式披露，Agent先看用途，需要时读SOP，执行时再加载详细规则、资产和脚本。",
    bullets: ["SKILL.md", "policies", "references", "schemas", "scripts", "examples"],
    visualType: "skill-architecture",
    sourceNote: "FullGoal PPT Master公开Skill结构",
    speakerNotes: notes(
      "1:35",
      ["Skill不是把所有规则塞进一个超长Prompt。", "渐进披露让Agent只在需要时读取详细材料。", "目录结构本身就是流程、边界和验证能力的载体。"],
      "案例验证之后，下一步是让成功流程可调用。",
      "最后看普通同事如何用三步开始。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "how-to-use",
    chapter: "skill",
    chapterLabel: "FullGoal PPT Master",
    pageNumber: 18,
    eyebrow: "PART 03 · HOW TO USE",
    title: "使用Skill，不需要先学会写代码",
    subtitle: "选择Skill、上传材料、逐阶段确认",
    keyMessage: "先要大纲和视觉建议，确认后再进入生产。",
    body: "示例任务：使用FullGoal PPT Master处理研究材料，先输出10页逐页大纲、核心内容与建议视觉，等待确认。",
    bullets: ["安装或选择Skill", "上传材料并提出任务", "逐阶段确认"],
    visualType: "demo-workflow",
    sourceNote: "本地模拟流程 · 不调用真实API",
    speakerNotes: notes(
      "1:40",
      ["普通同事只需要说明材料、目标和第一阶段交付物。", "关键是明确先不要直接生成最终页面。", "后续每个阶段都可以修改、选择或停止。"],
      "上一页解释了Skill内部是什么。",
      "回到今天的总命题：真正可复用的是流程、边界与验证。",
      "点击“运行演示”，观察流程在人工批准处停下。",
    ),
    assetSlots: ["skill-run"],
    theme: "light",
    status: "ready",
  },
  {
    id: "closing",
    chapter: "closing",
    chapterLabel: "结尾",
    pageNumber: 19,
    eyebrow: "ONE LAST THING",
    title: "真正可以复用的，不是某一句Prompt",
    subtitle: "而是Prompt背后的流程、边界和验证方法",
    keyMessage: "人定目标 · Chat帮助想清楚 · Agent负责做出来 · Skill负责重复使用",
    body: "当目标、责任与验收仍在人手中，AI才真正成为可持续的工作伙伴。",
    bullets: ["人：目标、判断和责任", "Chat：理解、规划和校准", "Agent：调用工具并完成执行", "Skill：沉淀可重复能力"],
    visualType: "closing",
    sourceNote: "内部交流 · 请勿外传",
    speakerNotes: notes(
      "0:50",
      ["最后只记住四句话就够了。", "人仍然负责目标、判断与责任。", "真正可复制的是Prompt背后的流程、边界和验证。"],
      "上一页把方法落到了普通同事的三步使用方式。",
      "谢谢大家，欢迎交流。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
];

export const sources: SourceItem[] = [
  {
    id: "openai-docs",
    title: "OpenAI官方产品与帮助文档",
    type: "官方文档",
    slideIds: ["ai-shift", "api-key", "agent-trends"],
    note: "用于支持AI、Agent、工具、Skills与Computer Use等基础概念和能力方向。",
  },
  {
    id: "agent-book",
    title: "AI Agent基础框架",
    type: "概念参考",
    slideIds: ["model-chat-agent", "concept-map", "thinking-frameworks"],
    note: "用于说明Model、Context、Tools、Harness与Human-in-the-loop的关系。",
  },
  {
    id: "fullgoal-public",
    title: "FullGoal PPT Master公开项目记录",
    type: "项目记录",
    slideIds: ["skill-problem", "project-evolution", "template-modes", "image-native-pivot", "skill-architecture", "how-to-use"],
    note: "用于支持公开Skill结构、模板骨架优先、A/B/C正文模式与阶段审批流程。",
  },
  {
    id: "ici-summary",
    title: "ICI测试项目脱敏总结",
    type: "用户提供材料",
    slideIds: ["ici-case"],
    note: "仅使用用户明确给出的页数、核验数字、大纲页数、代表页测试数与完成状态。",
  },
];

export const getSlideIndexFromHash = () => {
  const id = window.location.hash.replace(/^#/, "");
  const index = slides.findIndex((slide) => slide.id === id);
  return index >= 0 ? index : 0;
};
