import type { SlideData, SourceItem } from "../types/presentation";
import { timelineSources } from "./ai-evolution-timeline";

const notes = (
  duration: string,
  points: string[],
  bridgeFrom: string,
  transitionTo: string,
  action?: string,
) => ({ duration, points, bridgeFrom, transitionTo, action });

export const slides: SlideData[] = [
  {
    id: "hero",
    chapter: "opening",
    chapterLabel: "开场",
    pageNumber: 1,
    eyebrow: "FULLGOAL · AI SHARING SESSION",
    title: "AI不只是聊天",
    subtitle: "从Chat规划、Agent执行到Skill复用",
    keyMessage: "人定目标，Chat帮助想清楚，Agent负责做出来，Skill负责重复使用。",
    body: "一套面向普通同事的人机协作方法，以及一个真实Skill的设计过程。",
    bullets: ["内部分享", "2026"],
    visualType: "hero",
    sourceNote: "内部分享 · 请勿外传",
    speakerNotes: notes(
      "1:00",
      ["今天不讲模型参数，讲一套任何同事都能上手的工作方法。", "重点不是让AI替代谁，而是重新安排人、Chat、Agent与Skill的角色。"],
      "欢迎大家参加今天的内部分享。",
      "先用三件事建立今天的路线图。",
      "点击“开始分享”进入目录。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "agenda",
    chapter: "opening",
    chapterLabel: "开场",
    pageNumber: 2,
    eyebrow: "TODAY'S AGENDA",
    title: "今天主要分享三件事",
    subtitle: "从概念、方法到一个真实案例",
    keyMessage: "先看懂AI如何从回答问题走向完成工作，再看人怎样把复杂任务控制住。",
    body: "三个章节可点击跳转。",
    bullets: ["认识AI", "我的协作方法", "FullGoal PPT Master"],
    visualType: "agenda",
    sourceNote: "FG AI Sharing Session",
    speakerNotes: notes(
      "1:00",
      ["第一部分统一几个容易混淆的AI概念。", "第二部分分享我实际使用的六步SOP。", "第三部分拆解FullGoal PPT Master如何从需求演进成Skill。"],
      "刚才先给出了今天的总命题。",
      "先从AI正在发生的变化开始。",
      "可点击三个章节编号跳转。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "ai-shift",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 3,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "AI的变化，不只是回答更聪明，而是开始能够完成工作",
    subtitle: "从生成，到理解、行动与持续执行",
    keyMessage: "AI正在从“给答案的工具”，变成“参与工作过程的系统”。",
    body: "能力的关键变化，是从单次输出走向围绕目标的连续工作。",
    bullets: ["生成", "理解", "行动", "持续执行"],
    visualType: "ai-shift",
    sourceNote: "概念梳理：AI能力演进",
    speakerNotes: notes(
      "1:20",
      ["过去我们最熟悉的是让AI生成一段文字。", "现在AI还能读取项目上下文、调用工具，并根据结果决定下一步。", "四张卡片初始保持灰色；现场可逐张Hover或聚焦，让生成、理解、行动、持续执行依次恢复色彩和动态。", "变化的核心不是更会聊，而是开始进入工作过程。"],
      "目录把今天分成了三个部分。",
      "要理解这种变化，需要先区分模型、Chat与Agent。",
      "Hover、Tab聚焦或点击任意阶段；离开视频卡片后视频会暂停。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "model-chat-agent",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 4,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "模型、Chat和Agent，不是三个互相替代的产品",
    subtitle: "它们更像一条从能力内核、人机入口到任务系统的连续关系",
    keyMessage: "模型决定它能否理解和判断，上下文决定它能看到什么，工具决定它能做什么；持续的反馈循环，则决定它能否把任务真正完成。",
    body: "Model负责理解与生成；Chat让人方便使用模型；Agent围绕目标持续规划并调用工具。",
    bullets: ["Model / LLM", "Chat", "Agent"],
    visualType: "agent-formula",
    sourceNote: "参考：AI Agent基础框架",
    speakerNotes: notes(
      "1:30",
      ["左侧从能力内核、人机入口走到任务系统，三层是连续关系，不是互相替代。", "模型像大脑，Chat把文件、搜索与记忆带进上下文。", "Agent把Model、Context和Tools组织在一个目标下，并通过观察、规划、行动、验证、调整持续推进。", "现场可Hover Model、Chat、Agent，观察右侧对应模块和循环如何联动。"],
      "上一页讲的是AI从回答走向行动。",
      "接下来把常见的八个概念放到一张地图里。",
      "依次Hover左侧三层，强调能力—入口—系统的演进关系。",
    ),
    assetSlots: [],
    theme: "light",
    status: "ready",
  },
  {
    id: "concept-map",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 5,
    eyebrow: "PART 01 · AI FOUNDATION",
    title: "八个概念，基本可以看懂现在大多数AI产品",
    subtitle: "以Agent为中心，理解模型、材料、指令、工具与工作环境如何共同协作",
    keyMessage: "Agent的表现，不只取决于模型，也取决于它被放进了什么工作系统。",
    body: "移动鼠标探索知识星图；Hover聚焦，点击锁定，Agent或Esc恢复全局。",
    bullets: ["Model", "Context", "Prompt", "Tool", "API", "MCP", "Skill", "Harness"],
    visualType: "concept-map",
    sourceNote: "概念梳理：Agent工作系统；《AI大模型知识点全景图-73页》",
    speakerNotes: notes(
      "1:40",
      ["中央Agent不是第九个并列概念，而是把八个概念组织起来的行动系统。", "八颗主星对应Model、Context、Prompt、Tool、API、MCP、Skill与Harness；65颗次级星来自73页知识全景图与本项目既有教学框架。", "API Key已作为API知识簇中的独立节点保留，强调它是需要妥善保护的接口密钥。", "移动鼠标后标题会退到背景，Hover任意主星会展开其完整知识簇；点击可锁定并阅读节点附近的解释卡。"],
      "刚才用三层关系区分了模型、Chat与Agent。",
      "把这些概念放进时间轴，就能看见AI如何从对话入口走向可监督的工作系统。",
      "Hover、Tab聚焦或点击主星与重要次级星；点击中心Agent或按Esc恢复全局视图。",
    ),
    assetSlots: [],
    theme: "soft",
    status: "ready",
  },
  {
    id: "ai-evolution",
    chapter: "ai",
    chapterLabel: "认识AI",
    pageNumber: 6,
    eyebrow: "PART 01 · AI EVOLUTION",
    title: "从ChatGPT到Agent，AI在这几年发生了什么？",
    subtitle: "对话入口 → 多模态理解 → 深度推理 → 工具行动 → 长任务协作 → 人类监督",
    keyMessage: "今天AI竞争的重点，已经不只是模型更强，而是能否在工具、流程和监督下完成更长、更复杂的任务。",
    body: "四年时间，AI从会聊天的模型，逐渐演变为可以被组织和监督的工作系统。",
    bullets: ["Conversation", "Multimodality", "Reasoning", "Action", "Agent Era", "Human Steering"],
    visualType: "ai-evolution",
    sourceNote: "官方时间节点：OpenAI、Google、Anthropic、Meta、DeepSeek",
    speakerNotes: notes(
      "2:45",
      ["2022年的关键变化是对话入口，让普通人可以直接使用大模型。", "2023到2024年上半年，多模态、更快和更开放的模型让能力快速扩散。", "2024年下半年开始，深度推理成为主线；2025年则明显转向研究、浏览、编码和工具行动。", "2026年的重点不是再增加一个模型Logo，而是把长任务、并行Agent、工具操作、可复用Skills和Human Steering组织成工作系统。", "Hover或Tab聚焦节点查看解释，点击锁定；来源抽屉会按当前节点过滤官方材料。"],
      "上一页用知识宇宙说明了Agent工作系统的组成。",
      "能力演进之后，第二部分将说明我如何安排Chat、Agent与人的分工。",
      "依次Hover 2022、推理阶段、2025行动阶段和2026终点；点击2025后打开该节点来源。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "human-chat-agent-workflow",
    chapter: "method",
    chapterLabel: "协作方法",
    pageNumber: 7,
    eyebrow: "PART 02 · COLLABORATION METHOD",
    title: "人、Chat与Agent，怎样共同完成一项工作？",
    subtitle: "从目标、规划、批准到执行与复用，是一条持续反馈的协作链",
    keyMessage: "人定目标，Chat定方案，Agent做执行，验收控质量，Skill做复用。",
    body: "制作研究汇报的案例轨道，把六个角色与阶段产物放进同一条可控协作链。",
    bullets: ["Goal", "Plan", "Approve", "Execute", "Evaluate", "Reuse"],
    visualType: "human-chat-agent-workflow",
    sourceNote: "个人工作方法总结 · 结合Stage-Gate与Human-in-the-loop原则",
    speakerNotes: notes(
      "2:30",
      ["先由Human定义目标、提供材料并设定任务边界。", "Chat负责阅读、澄清和拆解，先形成可讨论的大纲与执行方案。", "第一个Human Gate批准方向后，Agent才分阶段调用工具、修改文件并生成产物。", "第二个Human Gate不听模型自评，而是检查事实、文件、截图和测试，决定通过或返工。", "稳定跑通的规则、流程与脚本最后才沉淀为Skill。", "页面底部用研究汇报案例说明：目标、规划、批准、生成、验收与PPT Skill复用是一条完整链路。"],
      "上一页说明了AI如何从对话入口走向可监督的工作系统。",
      "下一页解释这套方法建立在哪些成熟原则之上。",
      "Hover或Tab逐步探索；点击锁定；方向键切换节点；Esc清除。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "method-foundations",
    chapter: "method",
    chapterLabel: "协作方法",
    pageNumber: 8,
    eyebrow: "PART 02 · ENGINEERING FOUNDATIONS",
    title: "这套协作方法，本质上是一种工程化思维",
    subtitle: "先分解复杂度，再划分职责；通过迭代、评审与验证，把不确定任务变成可控过程",
    keyMessage: "我们没有发明新的工程原则，而是把成熟的分解、分工、迭代和验证思想应用到了Human—Chat—Agent协作中。",
    body: "中心是“把过程设计好”，四项原则形成可回流的工程反馈环。",
    bullets: ["Decompose Complexity", "Separation of Concerns", "Iterate with Feedback", "Verify before Accept"],
    visualType: "method-foundations",
    sourceNote: "NASA、Agile Manifesto、Microsoft、Google官方一手资料 · 业务化整合，非联合背书",
    speakerNotes: notes(
      "2:00",
      ["这一页不是在引用某个AI平台给出的Agent规则，而是在解释协作链背后的成熟工程思想。", "第一，NASA系统工程中的逻辑分解说明：面对复杂目标，先递归拆成可理解、可执行、可验证的下一层问题。", "第二，Microsoft架构模式中的职责分离说明：不同模块围绕清晰责任工作，通过接口协同，系统才更容易维护。", "第三，Agile Manifesto与Google工程实践强调频繁交付、小变更和持续反馈，让团队在局部修正而不是末尾推倒重来。", "第四，NASA产品验证与Google代码评审说明：完成声明不等于接受，必须依据预先定义的标准、测试和客观证据。", "我们没有发明新的工程原则，而是把分解、分工、迭代和验证转译到Human—Chat—Agent协作流程中。", "NASA、Microsoft、Agile Manifesto与Google没有联合批准或共同背书本框架；这些来源只证明相应工程思想已存在。"],
      "上一页给出了六步协作链。",
      "下面进入FullGoal PPT Master案例，看这些原则怎样落到真实产物。",
      "按顺时针方向介绍四个节点；Hover或Tab查看工程原义与协作转译，点击锁定，Esc清除，最后打开来源抽屉说明证据边界。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
  {
    id: "start-with-materials",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 9,
    eyebrow: "PART 03 · FROM MATERIALS TO DELIVERABLES",
    title: "一份研究材料，怎样开始变成一套汇报？",
    subtitle: "先提供资料和分析思路，再让AI理解材料、整理问题并提出大纲",
    keyMessage: "好的PPT不是从排版开始，而是从材料、问题和叙事方向开始。",
    body: "上传公开研究材料，明确分析问题，并限定当前只生成大纲。",
    bullets: ["材料输入", "分析思路", "Outline Only"], visualType: "start-with-materials",
    sourceNote: "ICI 2026 Investment Company Fact Book · Chapter 4 · 本地模拟交互",
    speakerNotes: notes("1:40", ["任务从公开材料与研究问题开始。", "这里明确要求先理解第四章并生成大纲，不直接生产页面。", "点击加载ICI演示任务，再发送并观察扫描状态。"], "第二部分给出了工程化协作方法。", "材料理解完成后，先讨论研究叙事。", "点击“加载ICI演示任务”与“发送并分析”。"),
    assetSlots: ["ici-public-material"], theme: "navy", status: "ready",
  },
  {
    id: "outline-before-slides",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 10,
    eyebrow: "PART 03 · OUTLINE APPROVAL",
    title: "AI先生成初稿，用户再把目录改造成研究叙事",
    subtitle: "大纲没有确认之前，不进入批量视觉生成",
    keyMessage: "AI负责形成可讨论的初稿，用户负责决定研究真正要回答什么。",
    body: "三处关键修改把统计目录重组为问题链，并形成10页确认版。",
    bullets: ["材料理解", "问题链重组", "人工批准门"], visualType: "outline-before-slides",
    sourceNote: "ICI第四章演示大纲 · FullGoal PPT Master Outline Approval",
    speakerNotes: notes("1:55", ["AI初版正确完整，但仍像原报告目录。", "三处修改分别改变开篇问题、交易机制和需求入口。", "显式确认后才允许进入A/B/C视觉探索。"], "材料已经进入上下文。", "确认研究叙事后，比较三种正文组织路线。", "先演示叙事修改，再点击“确认研究大纲”。"),
    assetSlots: ["ici-outline"], theme: "navy", status: "ready",
  },
  {
    id: "three-visual-routes",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 11,
    eyebrow: "PART 03 · VISUAL ROUTES",
    title: "同一页内容，可以有三种不同的视觉组织方式",
    subtitle: "固定品牌骨架不变，正文根据研究目的选择不同结构",
    keyMessage: "A/B/C不是三套企业品牌，而是固定品牌骨架内的三种内容组织方式。",
    body: "A结论与数据优先，B解释机制，C组合KPI、机制与启示。",
    bullets: ["A｜经典研究型", "B｜机制解释型", "C｜综合重点型"], visualType: "three-visual-routes",
    sourceNote: "现有A/B/C代表页素材 · 按页面内容重新映射",
    speakerNotes: notes("2:00", ["三张真实代表页共享同一品牌骨架。", "B方案以二级市场、一级市场申赎和底层资产为机制主轴。", "现场选择B并锁定后继续。"], "研究大纲已经确认。", "选定路线后进入生成与交付。", "Hover比较，点击锁定；现场可直接选择B。"),
    assetSlots: ["route-a-classic-research", "route-b-mechanism", "route-c-integrated"], theme: "navy", status: "ready",
  },
  {
    id: "generate-selected-route",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 12,
    eyebrow: "PART 03 · BUILD & DELIVERY",
    title: "选定视觉方向后，系统开始生成和整理交付产物",
    subtitle: "视觉生成、精确内容回填和文件输出是三个不同环节",
    keyMessage: "AI负责视觉，程序负责精确；Skill负责把两者组织成稳定交付。",
    body: "B方案作为代表Artifact继续推进，但不虚构完整13页或最终SVG/PPTX已经完成。",
    bullets: ["Image-native视觉", "精确内容回填", "分级输出"], visualType: "generate-selected-route",
    sourceNote: "Route B代表页 · 输出状态为流程演示",
    speakerNotes: notes("1:50", ["选定B后，视觉生成与精确内容回填分开进行。", "PNG预览可以提供；SVG仍是流程演示，PPTX需要单独构建。", "页面后的半透明轮廓只代表后续方向，不代表整套已经完成。"], "视觉路线已经锁定。", "下一页打开工作台，查看背后的生产流水线。", "点击“运行生成演示”查看阶段状态。"),
    assetSlots: ["route-b-mechanism"], theme: "navy", status: "partial",
  },
  {
    id: "behind-the-conversation",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 13,
    eyebrow: "PART 03 · PRODUCTION SYSTEM",
    title: "对话背后，运行的是一条有状态、有门禁的生产流水线",
    subtitle: "它不是一个很长的Prompt，而是一套可以暂停、批准、返工和验收的工作系统",
    keyMessage: "看起来是一次对话，实际运行的是一条受规则、状态和人工判断控制的生产线。",
    body: "研究决策层与视觉交付层通过来源和数据完整性链贯通。",
    bullets: ["Outline Approved?", "Visual Route Approved?", "Evidence Gate"], visualType: "behind-the-conversation",
    sourceNote: "FullGoal PPT Master公开Skill仓库 · Production SOP与Policy结构",
    speakerNotes: notes("2:10", ["上层负责材料、核验、叙事与大纲批准。", "下层负责A/B/C、代表页批准、Image-native、回填、QA和输出。", "数字、单位、时间、口径与来源必须贯穿全流程。"], "前四页展示了前台工作台。", "再用真实材料状态验证这条生产线。", "Hover流程节点查看Input、Output、Owner和Failure Path。"),
    assetSlots: [], theme: "navy", status: "ready",
  },
  {
    id: "real-material-validation",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 14,
    eyebrow: "PART 03 · REAL MATERIAL TEST",
    title: "这套流程已经用ICI公开材料进行真实验证",
    subtitle: "展示已经完成的部分，也明确尚未完成的部分",
    keyMessage: "真实测试的价值，不是证明所有工作已经完成，而是验证这条方法能否在真实材料上运行。",
    body: "146页Fact Book、第四章、26项核心数字、13页研究叙事和A/B/C代表视觉构成当前证据链。",
    bullets: ["PUBLIC SOURCE", "CHAPTER 4", "完成与未完成并列"], visualType: "real-material-validation",
    sourceNote: "ICI 2026 Investment Company Fact Book · Chapter 4",
    speakerNotes: notes("1:55", ["已完成第四章定位、提取、26项数字核验、13页叙事和A/B/C代表视觉。", "完整13页、最终SVG、可编辑PPTX和全套跨页QA仍未完成。", "未完成状态必须保留，因为它是证据可信度的一部分。"], "上一页解释了系统如何运行。", "最后说明为什么还需要工程控制。", "指向右侧真实B方案；Outline与QA保持明确占位。"),
    assetSlots: ["ici-public-cover", "route-b-mechanism", "ici-outline", "qa-result"], theme: "navy", status: "partial",
  },
  {
    id: "engineering-controls",
    chapter: "skill", chapterLabel: "FullGoal PPT Master", pageNumber: 15,
    eyebrow: "PART 03 · ENGINEERING CONTROLS",
    title: "为什么它最终需要被做成一个Skill？",
    subtitle: "可复用的关键不只是生成能力，而是边界、完整性、精确性、批准和验收",
    keyMessage: "真正可复用的不是某一张PPT，而是资料处理、人工批准、视觉生成、精确回填和质量验收组成的完整系统。",
    body: "五道工程控制轨道把风险信号转成可验证的控制结果。",
    bullets: ["Privacy Boundary", "Template Fingerprint", "Exact Content Recovery", "Approval Gates", "Evidence-based QA"], visualType: "engineering-controls",
    sourceNote: "FullGoal PPT Master公开Policy、Schema与QA控制设计",
    speakerNotes: notes("2:00", ["Public与Private必须物理隔离。", "正式模板通过SHA-256指纹校验，身份不一致时停止。", "Image-native后由程序回填精确内容，并通过人工批准和证据化QA。"], "真实材料证明方法可以运行。", "回到结尾：真正可复用的是Prompt背后的流程、边界和验证。", "Hover五项控制，观察Risk如何进入Control。"),
    assetSlots: [], theme: "navy", status: "ready",
  },
  {
    id: "closing",
    chapter: "closing",
    chapterLabel: "结尾",
    pageNumber: 16,
    eyebrow: "ONE LAST THING",
    title: "真正可以复用的，不是某一句Prompt",
    subtitle: "而是Prompt背后的流程、边界和验证方法",
    keyMessage: "人定目标 · Chat帮助想清楚 · Agent负责做出来 · Skill负责重复使用",
    body: "当目标、责任与验收仍在人手中，AI才真正成为可持续的工作伙伴。",
    bullets: ["人：目标、判断和责任", "Chat：理解、规划和校准", "Agent：调用工具并完成执行", "Skill：沉淀可重复能力"],
    visualType: "closing",
    sourceNote: "内部交流 · 请勿外传",
    speakerNotes: notes(
      "0:50",
      ["最后只记住四句话就够了。", "人仍然负责目标、判断与责任。", "真正可复制的是Prompt背后的流程、边界和验证。"],
      "上一页把方法收束为五项工程控制。",
      "谢谢大家，欢迎交流。",
    ),
    assetSlots: [],
    theme: "navy",
    status: "ready",
  },
];

export const sources: SourceItem[] = [
  {
    id: "openai-docs",
    title: "OpenAI官方产品与帮助文档",
    type: "官方文档",
    slideIds: ["ai-shift"],
    note: "用于支持AI、Agent、工具、Skills与Computer Use等基础概念和能力方向。",
  },
  {
    id: "ai-evolution-official",
    title: "AI Evolution官方时间节点",
    type: "官方公告与官方研究",
    slideIds: ["ai-evolution"],
    note: "按2022—2026能力阶段整理；时间线中的节点与趋势可进一步筛选对应来源。核验日期：2026-07-19。",
    entries: timelineSources,
  },
  {
    id: "agent-book",
    title: "AI Agent基础框架",
    type: "概念参考",
    slideIds: ["model-chat-agent", "concept-map", "method-foundations"],
    note: "用于说明Model、Context、Tools、Harness与Human-in-the-loop的关系。",
  },
  {
    id: "fullgoal-public",
    title: "FullGoal PPT Master公开项目记录",
    type: "项目记录",
    slideIds: ["start-with-materials", "outline-before-slides", "three-visual-routes", "generate-selected-route", "behind-the-conversation", "engineering-controls"],
    note: "用于支持公开Skill结构、固定品牌骨架、A/B/C正文模式、两个人工批准门、模板指纹与证据化QA。",
  },
  {
    id: "ici-summary",
    title: "ICI 2026 Investment Company Fact Book · Chapter 4",
    type: "公开研究材料与测试记录",
    slideIds: ["start-with-materials", "outline-before-slides", "three-visual-routes", "generate-selected-route", "real-material-validation"],
    note: "仅使用已确认的146页、第四章、26项数字核验、13页叙事重组、A/B/C代表视觉及当前未完成状态。",
  },
];

const legacyHashAliases: Record<string, string> = {
  "api-key": "ai-evolution",
  "agent-trends": "ai-evolution",
  "chat-vs-agent": "human-chat-agent-workflow",
  "collaboration-sop": "human-chat-agent-workflow",
  "stage-gate": "human-chat-agent-workflow",
  "stage-gates": "human-chat-agent-workflow",
  "thinking-framework": "method-foundations",
  "thinking-frameworks": "method-foundations",
  "skill-problem": "start-with-materials",
  "project-evolution": "outline-before-slides",
  "template-modes": "three-visual-routes",
  "image-native-pivot": "generate-selected-route",
  "ici-case": "real-material-validation",
  "skill-architecture": "behind-the-conversation",
  "how-to-use": "engineering-controls",
};

export const normalizeSlideId = (id: string) => legacyHashAliases[id] ?? id;

export const getSlideIndexFromHash = () => {
  const id = normalizeSlideId(window.location.hash.replace(/^#/, ""));
  const index = slides.findIndex((slide) => slide.id === id);
  return index >= 0 ? index : 0;
};
